# Generated by Django 5.1.4 on 2025-01-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('Temperature', 'Temperature'), ('Humidity', 'Humidity'), ('Soil Moisture', 'Soil Moisture'), ('Light Level', 'Light Level')], max_length=20)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_threshold', models.FloatField(default=30.0)),
                ('humidity_threshold', models.FloatField(default=70.0)),
                ('soil_moisture_threshold', models.FloatField(default=50.0)),
                ('light_level_threshold', models.FloatField(default=1000.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
